web:
  menu:
    baidu:
      url: http://www.baidu.com
      name: 百度
    ali:
      url: http://www.codecjh.top
      name: 自定义
    test:
      url: hh
      name: gogogogogo
zuul:
  routes:
    api-a:
      path: /auth/**
      serviceId: auth-server
    api-b:
      path: /gatewayhh/**
      url: forward:/gateway